### ISSUE TITLE
unbind js 报错

### ISSUE THREAD

**Issue by zxgfly** [huhuaaa/vue-lazyload#2]
for (i = 0; i < len; i++) {
                if (listeners[i].src == src) {//此处有可能报js错误
                    listeners.splice(i, 1)
                }
            }
}

**Comment by huhuaaa** [comment]
您好，可以提供出错的环境吗？方便修复，后续我也查看一下有没有这样的情况。

**Comment by huhuaaa** [comment]
您好，可以提供出错的环境吗？后续我也查看一下有没有这样的情况。感谢反馈！！！

**Comment by zxgfly** [comment]
for (i = 0; i < len; i++) {
    if (listeners[i].src == src) {
        listeners.splice(i, 1)//存在删除后  数组长度会有变化 len 超出listeners[i]
        len--
        i--
    }
}

**Comment by huhuaaa** [comment]
问题已经修复，感谢提醒！
